from ._colonyscopy import Plate, Colony, ColonyscopyFailedHeuristic
from .tools import smoothen, smoothen_image, expand_mask, color_distance

try:
	from .version import version as __version__
except ImportError:
	from warnings import warn
	warn('Failed to find (autogenerated) version.py. Do not worry about this unless you really need to know the version.')
